url: "https://collopy.net"
baseurl: ""
title: "Peter Sachs Collopy"
author: "Peter Sachs Collopy"

incremental: true

excerpt_separator: <!--more-->
permalink: /:categories/:year/:title/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-archives
  
feed:
  categories:
    - discussions
    - exhibits
    - presentations
    - teaching
    - writing
  posts_limit: 100
  tags:
    path: "/feed/research/"
    
pagination:
  enabled: true
  sort_reverse: true
  per_page: 15
  title: ':title, page :num of :max'

autopages:
  enabled: true
  categories:
    permalink: '/:cat'
  tags:
    permalink: '/research/:tag'
    title: 'On :tag'
    slugify:
      mode: 'pretty'

jekyll-archives:
  enabled:
    - year